"""Convert an existing Ultra HDR JPEG from BT.709 intents to Display P3.

The Ultra HDR container and gainmap metadata are regenerated by libultrahdr;
the source EXIF is inserted afterwards so camera metadata is retained.
"""
from pathlib import Path
import argparse
import subprocess
import tempfile

import numpy as np

from copy_exif_jpeg import copy_exif


M709 = np.array([
    [0.41239080, 0.35758434, 0.18048079],
    [0.21263901, 0.71516868, 0.07219232],
    [0.01933082, 0.11919478, 0.95053215],
], dtype=np.float32)
MP3 = np.array([
    [0.48657095, 0.26566769, 0.19821729],
    [0.22897456, 0.69173852, 0.07928691],
    [0.00000000, 0.04511338, 1.04394437],
], dtype=np.float32)
# RGB row vectors: p3 = 709 @ MATRIX.T
MATRIX = (np.linalg.inv(MP3) @ M709).astype(np.float32)


def add_legacy_gainmap_xmp(path):
    """Add the XMP container tag used by older Android HDR galleries.

    ISO 21496-1 remains the authoritative gainmap metadata. This compatibility
    tag only describes the second JPEG payload and does not replace APP2 data.
    """
    p = Path(path)
    data = p.read_bytes()
    first_eoi = data.find(b"\xff\xd9", 2)
    if first_eoi < 0:
        raise ValueError("JPEG has no primary image terminator")
    gainmap_length = len(data) - (first_eoi + 2)
    xmp = f'''<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="UltraHDR compatibility">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description xmlns:Container="http://ns.google.com/photos/1.0/container/"
      xmlns:Item="http://ns.google.com/photos/1.0/container/item/"
      xmlns:hdrgm="http://ns.adobe.com/hdr-gain-map/1.0/" hdrgm:Version="1.0">
      <Container:Directory><rdf:Seq>
        <rdf:li rdf:parseType="Resource"><Container:Item Item:Semantic="Primary" Item:Mime="image/jpeg"/></rdf:li>
        <rdf:li rdf:parseType="Resource"><Container:Item Item:Semantic="GainMap" Item:Mime="image/jpeg" Item:Length="{gainmap_length}"/></rdf:li>
      </rdf:Seq></Container:Directory>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>'''.encode()
    app1 = b"\xff\xe1" + (len(b"http://ns.adobe.com/xap/1.0/\x00") + len(xmp) + 2).to_bytes(2, "big") + b"http://ns.adobe.com/xap/1.0/\x00" + xmp
    p.write_bytes(data[:2] + app1 + data[2:])


def hlg_to_linear(x):
    a = 0.17883277
    b = 1 - 4 * a
    c = 0.5 - a * np.log(4 * a)
    return np.where(x <= 0.5, x * x / 3.0,
                    (np.exp((x - c) / a) + b) / 12.0)


def linear_to_hlg(x):
    a = 0.17883277
    b = 1 - 4 * a
    c = 0.5 - a * np.log(4 * a)
    x = np.clip(x, 0, None)
    with np.errstate(invalid="ignore", divide="ignore"):
        return np.where(x <= 1.0 / 12.0, np.sqrt(3.0 * x),
                        a * np.log(12.0 * x - b) + c)


def srgb_to_linear(x):
    x = np.clip(x, 0, 1)
    return np.where(x <= 0.04045, x / 12.92,
                    ((x + 0.055) / 1.055) ** 2.4)


def linear_to_srgb(x):
    x = np.clip(x, 0, 1)
    return np.where(x <= 0.0031308, 12.92 * x,
                    1.055 * np.power(x, 1 / 2.4) - 0.055)


def convert(src, exif_src, out, ultrahdr_app, target_nits=None, apply_matrix=True):
    # Read dimensions without decoding pixels through PIL (the base JPEG may
    # contain an HDR gainmap that PIL intentionally ignores).
    from PIL import Image
    with Image.open(src) as im:
        width, height = im.size
    with tempfile.TemporaryDirectory(prefix="uhdr_p3_") as td:
        td = Path(td)
        sdr709 = td / "sdr709.raw"
        hdr709 = td / "hdr709.raw"
        sdrp3 = td / "sdrp3.raw"
        hdrp3 = td / "hdrp3.raw"
        subprocess.run([str(ultrahdr_app), "-m", "1", "-j", str(src),
                        "-o", "3", "-O", "3", "-z", str(sdr709)], check=True)
        subprocess.run([str(ultrahdr_app), "-m", "1", "-j", str(src),
                        "-o", "1", "-O", "5", "-z", str(hdr709)], check=True)

        sdr = np.fromfile(sdr709, dtype=np.uint8).reshape(height, width, 4)[:, :, :3].astype(np.float32) / 255
        sdr_p3 = linear_to_srgb(srgb_to_linear(sdr) @ MATRIX.T) if apply_matrix else sdr
        out_sdr = np.full((height, width, 4), 255, dtype=np.uint8)
        out_sdr[:, :, :3] = np.round(sdr_p3 * 255).astype(np.uint8)
        out_sdr.tofile(sdrp3)

        packed = np.fromfile(hdr709, dtype=np.uint32).reshape(height, width)
        hdr = np.stack([(packed & 0x3ff), ((packed >> 10) & 0x3ff),
                        ((packed >> 20) & 0x3ff)], axis=-1).astype(np.float32) / 1023
        hdr_p3 = linear_to_hlg(hlg_to_linear(hdr) @ MATRIX.T) if apply_matrix else hdr
        vals = np.round(np.clip(hdr_p3, 0, 1) * 1023).astype(np.uint32)
        out_hdr = vals[:, :, 0] | (vals[:, :, 1] << 10) | (vals[:, :, 2] << 20) | (3 << 30)
        out_hdr.tofile(hdrp3)

        raw_out = td / "p3_uhdr.jpg"
        cmd = [str(ultrahdr_app), "-m", "0", "-p", str(hdrp3), "-y", str(sdrp3),
               "-w", str(width), "-h", str(height), "-a", "5", "-b", "3",
               "-t", "1", "-C", "1", "-c", "1", "-M", "0", "-q", "100",
               "-Q", "100", "-z", str(raw_out)]
        if target_nits is not None:
            cmd += ["-L", str(target_nits)]
        subprocess.run(cmd, check=True)
        if exif_src is not None:
            copy_exif(exif_src, raw_out, out)
        else:
            Path(out).write_bytes(raw_out.read_bytes())


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("exif_source")
    ap.add_argument("output")
    ap.add_argument("--ultrahdr-app", default="build/ultrahdr_app")
    ap.add_argument("--target-nits", type=float)
    ap.add_argument("--legacy-xmp", action="store_true")
    ap.add_argument("--no-matrix", action="store_true",
                    help="treat decoded values as already P3; only change container gamut")
    ap.add_argument("--no-exif", action="store_true")
    args = ap.parse_args()
    convert(Path(args.source), None if args.no_exif else Path(args.exif_source), Path(args.output),
            Path(args.ultrahdr_app), args.target_nits, not args.no_matrix)
    if args.legacy_xmp:
        add_legacy_gainmap_xmp(args.output)
